import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function downloadReceiptPDF(receipt) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const m = 20;
  const pageW = doc.internal.pageSize.getWidth();

  // header bar
  doc.setFillColor(30, 28, 24);
  doc.rect(0, 0, pageW, 18, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text("RECEIPT", m, 11);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(180, 175, 165);
  doc.text(`#${receipt.receipt_number}`, pageW - m, 11, { align: "right" });

  // vendor / customer block
  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(30, 28, 24);
  doc.text(receipt.vendor_name, m, 32);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 96, 90);
  doc.text("ISSUED TO", pageW - m - 60, 26);
  doc.setFontSize(11);
  doc.setTextColor(30, 28, 24);
  doc.text(receipt.customer_name, pageW - m - 60, 32);

  // meta row
  doc.setFontSize(8);
  doc.setTextColor(100, 96, 90);
  const date = receipt.date
    ? new Date(receipt.date).toLocaleDateString("en-CA")
    : "—";
  doc.text(`Date: ${date}`, m, 40);
  doc.text(`Status: ${receipt.status.toUpperCase()}`, m + 50, 40);

  // divider
  doc.setDrawColor(200, 196, 188);
  doc.setLineWidth(0.3);
  doc.line(m, 45, pageW - m, 45);

  // line items table
  const items = receipt.line_items?.length
    ? receipt.line_items.map((li) => [
        li.description,
        String(li.quantity),
        `$${parseFloat(li.unit_price).toFixed(2)}`,
        `$${parseFloat(li.total).toFixed(2)}`,
      ])
    : [["—", "", "", ""]];

  autoTable(doc, {
    startY: 50,
    head: [["Description", "Qty", "Unit Price", "Total"]],
    body: items,
    margin: { left: m, right: m },
    headStyles: {
      fillColor: [232, 230, 225],
      textColor: [100, 96, 90],
      fontSize: 7,
      fontStyle: "bold",
      halign: "left",
    },
    bodyStyles: { fontSize: 9, textColor: [50, 48, 44] },
    columnStyles: {
      0: { cellWidth: "auto" },
      1: { halign: "right", cellWidth: 20 },
      2: { halign: "right", cellWidth: 30 },
      3: { halign: "right", cellWidth: 30 },
    },
    theme: "plain",
    tableLineColor: [210, 208, 200],
    tableLineWidth: 0.2,
  });

  const y = doc.lastAutoTable.finalY + 6;

  // totals — right aligned block
  const col1 = pageW - m - 40;
  const col2 = pageW - m;

  doc.setDrawColor(200, 196, 188);
  doc.line(col1 - 5, y, col2, y);

  const rows = [
    ["Subtotal", `$${parseFloat(receipt.subtotal || 0).toFixed(2)}`],
    ["Tax", `$${parseFloat(receipt.tax || 0).toFixed(2)}`],
    ["Total", `$${parseFloat(receipt.total || 0).toFixed(2)}`],
  ];

  rows.forEach(([label, val], i) => {
    const ry = y + 8 + i * 8;
    const isTotal = label === "Total";

    if (isTotal) {
      doc.setDrawColor(150, 146, 138);
      doc.line(col1 - 5, ry - 4, col2, ry - 4);
    }

    doc.setFont("helvetica", isTotal ? "bold" : "normal");
    doc.setFontSize(isTotal ? 10 : 8);
    doc.setTextColor(isTotal ? 30 : 100, isTotal ? 28 : 96, isTotal ? 24 : 90);
    doc.text(label, col1, ry);
    doc.text(val, col2, ry, { align: "right" });
  });

  // notes
  if (receipt.notes) {
    const ny = y + 40;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(130, 126, 118);
    doc.text("Notes:", m, ny);
    doc.setTextColor(80, 78, 74);
    doc.text(receipt.notes, m, ny + 6, { maxWidth: pageW - m * 2 });
  }

  // footer
  doc.setFontSize(7);
  doc.setTextColor(180, 176, 168);
  doc.text("Generated by Receipt Generator", pageW / 2, 284, {
    align: "center",
  });

  doc.save(`receipt-${receipt.receipt_number}.pdf`);
}
