import { Resend } from "resend";
import { authenticate } from "./_lib.js";

const resend = new Resend(process.env.RESEND_API_KEY);

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const user = await authenticate(req, res);
  if (!user) return;

  const {
    to,
    vendor_name,
    customer_name,
    receipt_number,
    date,
    line_items,
    subtotal,
    tax,
    total,
    notes,
    payment_url,
  } = req.body;

  if (!to) return res.status(400).json({ error: "Recipient email is required" });

  const fmt = (n) => `$${parseFloat(n || 0).toFixed(2)}`;
  const dateStr = date ? new Date(date).toLocaleDateString("en-CA") : "—";

  const itemRows = (line_items ?? [])
    .map(
      (li) => `
      <tr>
        <td style="padding:8px 12px;border-bottom:1px solid #e8e6e1;">${li.description || "—"}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e8e6e1;text-align:right;">${li.quantity}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e8e6e1;text-align:right;">${fmt(li.unit_price)}</td>
        <td style="padding:8px 12px;border-bottom:1px solid #e8e6e1;text-align:right;">${fmt(li.total)}</td>
      </tr>`
    )
    .join("");

  const html = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f5f4f0;font-family:helvetica,arial,sans-serif;">
  <div style="max-width:560px;margin:32px auto;background:#fff;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,0.08);">

    <div style="background:#1e1c18;padding:20px 28px;">
      <span style="color:#fff;font-size:13px;font-weight:700;letter-spacing:0.1em;">RECEIPT</span>
      <span style="color:#b4afa5;font-size:11px;float:right;line-height:20px;">#${receipt_number}</span>
    </div>

    <div style="padding:24px 28px 0;">
      <table width="100%" style="margin-bottom:20px;">
        <tr>
          <td style="vertical-align:top;">
            <div style="font-size:11px;color:#908e8a;margin-bottom:4px;">FROM</div>
            <div style="font-size:14px;font-weight:700;color:#1e1c18;">${vendor_name || "—"}</div>
          </td>
          <td style="vertical-align:top;text-align:right;">
            <div style="font-size:11px;color:#908e8a;margin-bottom:4px;">ISSUED TO</div>
            <div style="font-size:14px;font-weight:700;color:#1e1c18;">${customer_name || "—"}</div>
          </td>
        </tr>
      </table>
      <div style="font-size:11px;color:#908e8a;margin-bottom:20px;">Date: ${dateStr}</div>
    </div>

    <table width="100%" style="border-collapse:collapse;margin:0 0 0 0;">
      <thead>
        <tr style="background:#f0ede8;">
          <th style="padding:8px 12px;text-align:left;font-size:10px;color:#908e8a;font-weight:600;">DESCRIPTION</th>
          <th style="padding:8px 12px;text-align:right;font-size:10px;color:#908e8a;font-weight:600;">QTY</th>
          <th style="padding:8px 12px;text-align:right;font-size:10px;color:#908e8a;font-weight:600;">PRICE</th>
          <th style="padding:8px 12px;text-align:right;font-size:10px;color:#908e8a;font-weight:600;">TOTAL</th>
        </tr>
      </thead>
      <tbody>${itemRows || `<tr><td colspan="4" style="padding:12px;color:#908e8a;font-size:12px;">No line items</td></tr>`}</tbody>
    </table>

    <div style="padding:20px 28px;">
      ${parseFloat(subtotal) > 0 ? `<div style="display:flex;justify-content:space-between;font-size:12px;color:#908e8a;margin-bottom:6px;"><span>Subtotal</span><span>${fmt(subtotal)}</span></div>` : ""}
      ${parseFloat(tax) > 0 ? `<div style="display:flex;justify-content:space-between;font-size:12px;color:#908e8a;margin-bottom:10px;"><span>Tax</span><span>${fmt(tax)}</span></div>` : ""}
      <div style="display:flex;justify-content:space-between;font-size:16px;font-weight:700;color:#1e1c18;border-top:1px solid #e8e6e1;padding-top:12px;">
        <span>Total</span><span>${fmt(total)}</span>
      </div>
      ${notes ? `<div style="margin-top:20px;font-size:11px;color:#908e8a;border-top:1px solid #e8e6e1;padding-top:16px;"><strong>Note:</strong> ${notes}</div>` : ""}
      ${payment_url ? `
      <div style="text-align:center;margin-top:24px;">
        <a href="${payment_url}" style="display:inline-block;background:#1e1c18;color:#fff;text-decoration:none;padding:12px 28px;border-radius:6px;font-size:13px;font-weight:600;">Pay Now</a>
      </div>` : ""}
    </div>

    <div style="background:#f5f4f0;padding:14px 28px;text-align:center;font-size:10px;color:#b4afa5;">
      Generated by Keep Track · Receipt Generator
    </div>
  </div>
</body>
</html>`;

  try {
    await resend.emails.send({
      from: "invoices@keeptrack.app",
      to,
      subject: `Invoice #${receipt_number} from ${vendor_name || "your vendor"}`,
      html,
      reply_to: user.email || undefined,
    });
    return res.json({ ok: true });
  } catch (err) {
    console.error("send-invoice:", err.message);
    return res.status(500).json({ error: err.message });
  }
}
